import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Link from 'next/link';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faMugHot } from '@fortawesome/free-solid-svg-icons';

import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="mb-16">
          <div className="max-w-2xl flex justify-between mx-auto px-4 py-4">
            <Link href={'/'} className="inline-flex gap-1 items-center">
              <FontAwesomeIcon icon={faMugHot} className="h-8" />
              <span className="mt-2">Buy me a coffee</span>
            </Link>
            <nav className="mt-2 flex items-center gap-6">
              <Link href="/about">About</Link>
              <Link href="/about">FAQ</Link>
              <Link href="/about">Contact</Link>
              <div className="flex gap-4">
                <button className="border-2 rounded-full px-4 py-2 ml-4">
                  Login
                </button>
                <button className="bg-yellow-300 rounded-full py-2 px-4 ml-4">
                  Sign up
                </button>
              </div>
            </nav>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
